# Generated by Django 2.1.7 on 2019-06-12 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name_plural': 'Node'},
        ),
        migrations.AddField(
            model_name='node',
            name='nid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
