# Generated by Django 2.1.7 on 2019-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190612_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
