# Generated by Django 2.1.7 on 2019-06-15 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_node_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='nid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
